# Generated by Django 4.1.1 on 2022-10-19 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tb_1',
            name='calcaualte_type',
            field=models.CharField(choices=[('0', '加法'), ('1', '減法'), ('2', '乘法'), ('3', '除法')], default='0', max_length=1),
        ),
    ]
