# Generated by Django 4.1.1 on 2022-10-19 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_tb_1_calcaualte_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tb_1',
            old_name='calcaualte_type',
            new_name='type',
        ),
    ]
