# Generated by Django 4.1.1 on 2022-10-19 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_rename_calcaualte_type_tb_1_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tb_1',
            options={'verbose_name': '用戶資料庫', 'verbose_name_plural': '用戶資料庫'},
        ),
    ]
