# Generated by Django 4.1.1 on 2022-10-20 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-_time'], 'verbose_name': '用戶資料庫', 'verbose_name_plural': '用戶資料庫'},
        ),
    ]
