# Generated by Django 4.1.1 on 2022-10-28 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_alter_user_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='question',
            field=models.CharField(default=1, max_length=64),
            preserve_default=False,
        ),
    ]
