# Generated by Django 4.1.1 on 2022-10-27 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ema', '0002_tb_1__time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tb_1',
            options={'ordering': ['-_time'], 'verbose_name': '問題歷史記錄', 'verbose_name_plural': '問題歷史紀錄'},
        ),
    ]
