# Generated by Django 4.1.1 on 2022-10-27 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ema', '0003_alter_tb_1_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='tb_1',
            name='name',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
